<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgGuA8w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgGuA8w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMgGuA8w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMgGuA8w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMgGuA8w\App_KernelDevDebugContainer([
    'container.build_hash' => 'MgGuA8w',
    'container.build_id' => '03f67014',
    'container.build_time' => 1734638249,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgGuA8w');
