<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWiQdbX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWiQdbX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPWiQdbX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPWiQdbX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPWiQdbX\App_KernelDevDebugContainer([
    'container.build_hash' => 'PWiQdbX',
    'container.build_id' => 'a0f1efc9',
    'container.build_time' => 1736491620,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWiQdbX');
